/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as RobotsImport } from './routes/robots'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as ConnectImport } from './routes/connect'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as ConnectRobotIdImport } from './routes/connect.$robotId'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutRobotsImport } from './routes/_layout/robots'
import { Route as LayoutConnectImport } from './routes/_layout/connect'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutConnectRobotIdImport } from './routes/_layout/connect.$robotId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const RobotsRoute = RobotsImport.update({
  path: '/robots',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ConnectRoute = ConnectImport.update({
  path: '/connect',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const ConnectRobotIdRoute = ConnectRobotIdImport.update({
  path: '/$robotId',
  getParentRoute: () => ConnectRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRobotsRoute = LayoutRobotsImport.update({
  path: '/robots',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutConnectRoute = LayoutConnectImport.update({
  path: '/connect',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutConnectRobotIdRoute = LayoutConnectRobotIdImport.update({
  path: '/$robotId',
  getParentRoute: () => LayoutConnectRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/connect': {
      preLoaderRoute: typeof ConnectImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/robots': {
      preLoaderRoute: typeof RobotsImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/connect': {
      preLoaderRoute: typeof LayoutConnectImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/robots': {
      preLoaderRoute: typeof LayoutRobotsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/connect/$robotId': {
      preLoaderRoute: typeof ConnectRobotIdImport
      parentRoute: typeof ConnectImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/connect/$robotId': {
      preLoaderRoute: typeof LayoutConnectRobotIdImport
      parentRoute: typeof LayoutConnectImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutConnectRoute.addChildren([LayoutConnectRobotIdRoute]),
    LayoutRobotsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  ConnectRoute.addChildren([ConnectRobotIdRoute]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  RobotsRoute,
  SignupRoute,
])

/* prettier-ignore-end */
