"""init

Revision ID: 600a2c7cff8a
Revises: b9619916096f
Create Date: 2025-05-12 13:12:42.011380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '600a2c7cff8a'
down_revision = 'b9619916096f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
