// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  DashboardReadDashboardResponse,
  DashboardUpsertDashboardData,
  DashboardUpsertDashboardResponse,
  DynamicTypeConfigDeleteDynamicTypeConfigResponse,
  DynamicTypeConfigReadDynamicTypeConfigResponse,
  DynamicTypeConfigUpsertDynamicTypeConfigData,
  DynamicTypeConfigUpsertDynamicTypeConfigResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  RobotsCreateRobotData,
  RobotsCreateRobotResponse,
  RobotsDeleteRobotData,
  RobotsDeleteRobotResponse,
  RobotsReadRobotData,
  RobotsReadRobotResponse,
  RobotsReadRobotsData,
  RobotsReadRobotsResponse,
  RobotsUpdateRobotData,
  RobotsUpdateRobotResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserMeResponse,
  UsersDeleteUserResponse,
  UsersDisconnectExistingSessionData,
  UsersDisconnectExistingSessionResponse,
  UsersLoginAccessTokenData,
  UsersLoginAccessTokenResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersRecoverPasswordData,
  UsersRecoverPasswordHtmlContentData,
  UsersRecoverPasswordHtmlContentResponse,
  UsersRecoverPasswordResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersResetPasswordData,
  UsersResetPasswordResponse,
  UsersTestTokenResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersUpdateUserData,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
  UtilsHealthCheckResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
} from "./types.gen"

export class DashboardService {
  /**
   * Read Dashboard
   * 현재 사용자의 대시보드 설정 조회
   * @returns DashboardPublic Successful Response
   * @throws ApiError
   */
  public static readDashboard(): CancelablePromise<DashboardReadDashboardResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/dashboard",
    })
  }

  /**
   * Upsert Dashboard
   * 대시보드 설정 upsert (있으면 업데이트, 없으면 생성)
   * @param data The data for the request.
   * @param data.requestBody
   * @returns DashboardPublic Successful Response
   * @throws ApiError
   */
  public static upsertDashboard(
    data: DashboardUpsertDashboardData,
  ): CancelablePromise<DashboardUpsertDashboardResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/dashboard",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DynamicTypeConfigService {
  /**
   * Read Dynamic Type Config
   * 현재 사용자의 동적 타입 설정 조회
   * @returns DynamicTypeConfigPublic Successful Response
   * @throws ApiError
   */
  public static readDynamicTypeConfig(): CancelablePromise<DynamicTypeConfigReadDynamicTypeConfigResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/dynamic-type-config/",
    })
  }

  /**
   * Upsert Dynamic Type Config
   * 동적 타입 설정 upsert (있으면 업데이트, 없으면 생성)
   * @param data The data for the request.
   * @param data.requestBody
   * @returns DynamicTypeConfigPublic Successful Response
   * @throws ApiError
   */
  public static upsertDynamicTypeConfig(
    data: DynamicTypeConfigUpsertDynamicTypeConfigData,
  ): CancelablePromise<DynamicTypeConfigUpsertDynamicTypeConfigResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/dynamic-type-config/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Dynamic Type Config
   * 현재 사용자의 동적 타입 설정 삭제
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteDynamicTypeConfig(): CancelablePromise<DynamicTypeConfigDeleteDynamicTypeConfigResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/dynamic-type-config/",
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns LoginResponse Successful Response
   * @throws ApiError
   */
  public static usersLoginAccessToken(
    data: UsersLoginAccessTokenData,
  ): CancelablePromise<UsersLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Disconnect Existing Session
   * Disconnect existing WebSocket connection and force logout
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersDisconnectExistingSession(
    data: UsersDisconnectExistingSessionData,
  ): CancelablePromise<UsersDisconnectExistingSessionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/disconnect",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersTestToken(): CancelablePromise<UsersTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersRecoverPassword(
    data: UsersRecoverPasswordData,
  ): CancelablePromise<UsersRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersResetPassword(
    data: UsersResetPasswordData,
  ): CancelablePromise<UsersResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static usersRecoverPasswordHtmlContent(
    data: UsersRecoverPasswordHtmlContentData,
  ): CancelablePromise<UsersRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class RobotsService {
  /**
   * Read Robots
   * Retrieve robots.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns RobotsPublic Successful Response
   * @throws ApiError
   */
  public static readRobots(
    data: RobotsReadRobotsData = {},
  ): CancelablePromise<RobotsReadRobotsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/robots/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Robot
   * Create new robot.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns RobotPublic Successful Response
   * @throws ApiError
   */
  public static createRobot(
    data: RobotsCreateRobotData,
  ): CancelablePromise<RobotsCreateRobotResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/robots/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Robot
   * Get robot by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns RobotPublic Successful Response
   * @throws ApiError
   */
  public static readRobot(
    data: RobotsReadRobotData,
  ): CancelablePromise<RobotsReadRobotResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/robots/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Robot
   * Update a robot.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns RobotPublic Successful Response
   * @throws ApiError
   */
  public static updateRobot(
    data: RobotsUpdateRobotData,
  ): CancelablePromise<RobotsUpdateRobotResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/robots/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Robot
   * Delete a robot.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteRobot(
    data: RobotsDeleteRobotData,
  ): CancelablePromise<RobotsDeleteRobotResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/robots/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns LoginResponse Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: UsersLoginAccessTokenData,
  ): CancelablePromise<UsersLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Disconnect Existing Session
   * Disconnect existing WebSocket connection and force logout
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static disconnectExistingSession(
    data: UsersDisconnectExistingSessionData,
  ): CancelablePromise<UsersDisconnectExistingSessionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/disconnect",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<UsersTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: UsersRecoverPasswordData,
  ): CancelablePromise<UsersRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: UsersResetPasswordData,
  ): CancelablePromise<UsersResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: UsersRecoverPasswordHtmlContentData,
  ): CancelablePromise<UsersRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
