// This file is auto-generated by @hey-api/openapi-ts

export type Body_users_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type DashboardCreate = {
  dashboard_config?: {
    [key: string]: unknown
  }
}

export type DashboardPublic = {
  dashboard_config?: {
    [key: string]: unknown
  }
  dashboard_id: string
  user_id: string
  created_at: string
  updated_at: string
}

export type DisconnectRequest = {
  user_id: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type LoginResponse = {
  access_token: string
  existing_connection?: boolean
  message?: string | null
  user_id?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type RobotCreate = {
  name: string
  description?: string | null
  status?: RobotStatus
  id?: string | null
}

export type RobotPublic = {
  name: string
  description?: string | null
  status?: RobotStatus
  id: string
  owner_id: string
}

export type RobotsPublic = {
  data: Array<RobotPublic>
  count: number
}

export type RobotStatus =
  | "READY_TO_CONNECT"
  | "CONNECTING"
  | "CONNECTED"
  | "DISCONNECTED"
  | "REMOVED"

export type RobotUpdate = {
  name?: string | null
  description?: string | null
  status?: RobotStatus | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type DashboardReadDashboardResponse = DashboardPublic

export type DashboardUpsertDashboardData = {
  requestBody: DashboardCreate
}

export type DashboardUpsertDashboardResponse = DashboardPublic

export type UsersLoginAccessTokenData = {
  formData: Body_users_login_access_token
}

export type UsersLoginAccessTokenResponse = LoginResponse

export type UsersDisconnectExistingSessionData = {
  requestBody: DisconnectRequest
}

export type UsersDisconnectExistingSessionResponse = Message

export type UsersTestTokenResponse = UserPublic

export type UsersRecoverPasswordData = {
  email: string
}

export type UsersRecoverPasswordResponse = Message

export type UsersResetPasswordData = {
  requestBody: NewPassword
}

export type UsersResetPasswordResponse = Message

export type UsersRecoverPasswordHtmlContentData = {
  email: string
}

export type UsersRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type RobotsReadRobotsData = {
  limit?: number
  skip?: number
}

export type RobotsReadRobotsResponse = RobotsPublic

export type RobotsCreateRobotData = {
  requestBody: RobotCreate
}

export type RobotsCreateRobotResponse = RobotPublic

export type RobotsReadRobotData = {
  id: string
}

export type RobotsReadRobotResponse = RobotPublic

export type RobotsUpdateRobotData = {
  id: string
  requestBody: RobotUpdate
}

export type RobotsUpdateRobotResponse = RobotPublic

export type RobotsDeleteRobotData = {
  id: string
}

export type RobotsDeleteRobotResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdate
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
