package com.gistacsl.mosaic.common.enumerate;

import lombok.Getter;
import org.springframework.http.HttpStatus;

public enum ResultCode implements SerializableEnum {
    SUCCESS(100, "OK", HttpStatus.OK),

    UNKNOWN_EXCEPTION_OCCURRED(10000, "UNKNOWN_EXCEPTION_OCCURRED", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_FORMAT(10001, "INVALID_FORMAT", HttpStatus.BAD_REQUEST),
    UNKNOWN_WEBSOCKET_REQUEST_TYPE(10002, "UNKNOWN_WEBSOCKET_REQUEST_TYPE", HttpStatus.BAD_REQUEST),

    ACCESS_TOKEN_GENERATION_FAILED(2011, "Access Token Generation Failed", HttpStatus.CONFLICT),
    REFRESH_TOKEN_GENERATION_FAILED(2012, "Refresh Token Generation Failed", HttpStatus.CONFLICT),
    JWT_TOKEN_UNEXPECTED_ERROR(10013, "JWT_TOKEN_UNEXPECTED_ERROR", HttpStatus.UNAUTHORIZED),

    JWT_TOKEN_NOT_SUPPORTED(2009, "JWT Token Not Supported", HttpStatus.FORBIDDEN),
    ACCESS_TOKEN_NOT_EXIST(2015, "Access Token Not Exist", HttpStatus.FORBIDDEN),
    ACCESS_TOKEN_DECRYPTING_FAILED(2002, "Decrypting Access Token Failed", HttpStatus.FORBIDDEN),
    ACCESS_TOKEN_EXPIRED(2004, "Access Token expired", HttpStatus.FORBIDDEN),
    REFRESH_TOKEN_EXPIRED(2005, "Refresh Token expired", HttpStatus.FORBIDDEN),
    REFRESH_TOKEN_NOT_EXIST(2006, "Refresh Token Not Exist", HttpStatus.FORBIDDEN),
    REFRESH_TOKEN_DECRYPTING_FAILED(2003, "Decrypting Refresh Token Failed", HttpStatus.FORBIDDEN),

    ACCESS_DENIED(10020, "ACCESS_DENIED", HttpStatus.FORBIDDEN),
    AUTHENTICATION_FAILED(10021, "AUTHENTICATION_FAILED", HttpStatus.UNAUTHORIZED),
    CANNOT_FIND_USER_AUTH_FROM_CONTEXT(10022, "CANNOT_FIND_USER_AUTH_FROM_CONTEXT", HttpStatus.UNAUTHORIZED),

    WEBSOCKET_SESSION_NOT_EXIST(10050, "WEBSOCKET_SESSION_NOT_EXIST", HttpStatus.BAD_REQUEST),
    ROBOT_WS_SESSION_NOT_EXIST(10051, "ROBOT_WS_SESSION_NOT_EXIST", HttpStatus.BAD_REQUEST),
    USER_WS_SESSION_NOT_EXIST(10052, "USER_WS_SESSION_NOT_EXIST", HttpStatus.BAD_REQUEST),
    WEBRTC_SESSION_NOT_EXIST(10053, "WEBRTC_SESSION_NOT_EXIST", HttpStatus.BAD_REQUEST),
    UNKNOWN_ROBOT_AUTH_TYPE(10054, "UNKNOWN_ROBOT_AUTH_TYPE", HttpStatus.BAD_REQUEST),
    INVALID_ROBOT_AUTH_TYPE(10055, "INVALID_ROBOT_AUTH_TYPE", HttpStatus.BAD_REQUEST),

    // User/Account errors
    USER_NOT_FOUND(10060, "USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    USER_NOT_ACTIVE(10061, "USER_NOT_ACTIVE", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(10062, "INVALID_PASSWORD", HttpStatus.BAD_REQUEST),
    NOT_IMPLEMENTED(10063, "NOT_IMPLEMENTED", HttpStatus.NOT_IMPLEMENTED),
    USER_ALREADY_EXISTS(10064, "USER_ALREADY_EXISTS", HttpStatus.BAD_REQUEST),
    DB_USER_CREATE_FAILED(10065, "DB_USER_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_USER_READ_FAILED(10066, "DB_USER_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_USER_UPDATE_FAILED(10067, "DB_USER_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_USER_DELETE_FAILED(10068, "DB_USER_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    CANNOT_DELETE_YOURSELF(10069, "CANNOT_DELETE_YOURSELF", HttpStatus.FORBIDDEN),

    // Organization errors
    DB_ORGANIZATION_CREATE_FAILED(10070, "DB_ORGANIZATION_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_ORGANIZATION_READ_FAILED(10071, "DB_ORGANIZATION_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // Occupancy Map errors
    OCCUPANCY_MAP_NOT_FOUND(10080, "OCCUPANCY_MAP_NOT_FOUND", HttpStatus.NOT_FOUND),
    DB_OCCUPANCY_MAP_CREATE_FAILED(10081, "DB_OCCUPANCY_MAP_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_OCCUPANCY_MAP_READ_FAILED(10082, "DB_OCCUPANCY_MAP_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_OCCUPANCY_MAP_UPDATE_FAILED(10083, "DB_OCCUPANCY_MAP_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_OCCUPANCY_MAP_DELETE_FAILED(10084, "DB_OCCUPANCY_MAP_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // Robot errors
    ROBOT_NOT_FOUND(20001, "ROBOT_NOT_FOUND", HttpStatus.NOT_FOUND),
    DB_ROBOT_CREATE_FAILED(20002, "DB_ROBOT_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_ROBOT_READ_FAILED(20003, "DB_ROBOT_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_ROBOT_UPDATE_FAILED(20004, "DB_ROBOT_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_ROBOT_DELETE_FAILED(20005, "DB_ROBOT_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    TAB_NOT_FOUND(20001, "TAB_NOT_FOUND", HttpStatus.NOT_FOUND),
    DB_TAB_CREATE_FAILED(20002, "DB_TAB_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_TAB_READ_FAILED(20003, "DB_TAB_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_TAB_UPDATE_FAILED(20004, "DB_TAB_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_TAB_DELETE_FAILED(20005, "DB_TAB_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // Key Pair errors
    DB_KEY_PAIR_CREATE_FAILED(30001, "DB_KEY_PAIR_CREATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    DB_KEY_PAIR_READ_FAILED(30002, "DB_KEY_PAIR_READ_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ;

    private final int value;

    @Getter
    private final String description;

    @Getter
    private final HttpStatus httpStatus;

    ResultCode(int value, String description, HttpStatus httpStatus) {
        this.value = value;
        this.description = description;
        this.httpStatus = httpStatus;
    }

    @Override
    public int getValue() {
        return this.value;
    }

}