"""Add Occupancy map name field

Revision ID: 1097b9728ca0
Revises: d97b0a226474
Create Date: 2025-10-29 19:18:21.892396

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1097b9728ca0'
down_revision = 'd97b0a226474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy_map', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy_map', 'name')
    # ### end Alembic commands ###
