"""add dynamic type config table

Revision ID: ad9accb55982
Revises: dfae5f9e005a
Create Date: 2025-07-28 17:50:21.513035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad9accb55982'
down_revision = 'dfae5f9e005a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_type_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_type_config_user_id'), 'dynamic_type_config', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_type_config_user_id'), table_name='dynamic_type_config')
    op.drop_table('dynamic_type_config')
    # ### end Alembic commands ###
