"""redefine robot status enum

Revision ID: b70ad3570f3d
Revises: ad9accb55982
Create Date: 2025-08-03 20:17:22.520964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b70ad3570f3d'
down_revision = 'ad9accb55982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum values to existing robotstatus enum
    op.execute("ALTER TYPE robotstatus ADD VALUE IF NOT EXISTS 'DISCONNECTING'")
    op.execute("ALTER TYPE robotstatus ADD VALUE IF NOT EXISTS 'FAILED'")
    op.execute("ALTER TYPE robotstatus ADD VALUE IF NOT EXISTS 'SHUTTING_DOWN'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # You would need to recreate the enum type if you really need to remove values
    # For now, we'll leave the enum values as they are
    #
    # If you absolutely need to remove them, you'd need to:
    # 1. Create a new enum type without the unwanted values
    # 2. Alter the column to use the new type
    # 3. Drop the old enum type
    # 4. Rename the new type to the original name

    # Uncomment and modify if you need strict downgrade:
    op.execute("""
        CREATE TYPE robotstatus_old AS ENUM (
            'READY_TO_CONNECT', 'CONNECTING', 'CONNECTED', 'DISCONNECTED', 'REMOVED'
        )
    """)
    op.execute("ALTER TABLE robot ALTER COLUMN status TYPE robotstatus_old USING status::text::robotstatus_old")
    op.execute("DROP TYPE robotstatus")
    op.execute("ALTER TYPE robotstatus_old RENAME TO robotstatus")
    # ### end Alembic commands ###
