@startuml
'https://plantuml.com/sequence-diagram

participant WidgetComponent
participant WriteOnlyStore
participant WebRTCConnection
participant Robot

autonumber

== 데이터 송신 ==

WidgetComponent -[#red]> WriteOnlyStore: add(data)
WriteOnlyStore -[#red]> WriteOnlyStore ++: parser(data)
WriteOnlyStore [#blue]-> WriteOnlyStore --: 파싱된 데이터

WriteOnlyStore -[#red]> WebRTCConnection: sendData(channelLabel, data)
WebRTCConnection -[#red]> WebRTCConnection ++: DataChannel.send(data)
WebRTCConnection [#blue]-> WebRTCConnection --: 데이터 전송

WebRTCConnection -[#red]> Robot: 데이터 전송 (DataChannel)
Robot [#blue]-> Robot: 데이터 수신 및 처리
@enduml