@startuml
skinparam sequenceMessageAlign center
skinparam maxMessageSize 250
autonumber

participant DashboardGrid
participant MosaicContext
participant RobotInfo
participant WebRTCConnectionManager
participant WebRTCConnection
participant MosaicStore
participant RTCDataChannel
participant SignalingServer
participant Backend
participant Robot

== 로봇 연결 시작 ==

DashboardGrid -[#red]> MosaicContext: requestConnection(robotId)
activate MosaicContext

== WebSocket 연결 ==

MosaicContext -[#red]> RobotInfo: updateRobotInfo(robotInfo)
activate RobotInfo
RobotInfo -[#black]> RobotInfo: robotInfo 객체 교체
RobotInfo --[#blue]> MosaicContext: 완료
deactivate RobotInfo
note over MosaicContext, RobotInfo: 이것 역시 updateRobotInfo() 주체는 미정, (set method만 삭제함)

== WebRTC 연결 시작 ==
MosaicContext -[#red]> WebRTCConnectionManager: 내부 connections 참조 (key = robotId)
WebRTCConnectionManager -[#blue]> MosaicContext : WebRTCConnection | undefined

alt 해당 robotId의 WebRTCConnection이 존재할 경우
 MosaicContext -[#red]> WebRTCConnectionManager : disconnectConnection(robotId)
 WebRTCConnectionManager -[#blue]> MosaicContext : 완료

else 없는 경우
 MosaicContext -[#red]> WebRTCConnectionManager: createConnection(robotId, channelRequirements)
 activate WebRTCConnectionManager
end



WebRTCConnectionManager -[#red]> Backend: API 호출 POST /api/v1/connection/create
note right of WebRTCConnectionManager
{
    "robotId": "e8715ad5-7a19-4733-9692-ec5572d6de7c"
}
end note
Backend -> Backend: WebRTC 연결을 위한 RTC Connection ID 생성, 저장
WebRTCConnectionManager <[#blue]- Backend: RTC Connection ID 응답
note right of WebRTCConnectionManager
{
    "rtcConnectionId": "d1c35a55-445c-4e5e-9451-34c42d74fcbd"
}
end note

create WebRTCConnection
WebRTCConnectionManager -[#black]> WebRTCConnection: new WebRTCConnection(rtcConnectionId, robotId)

WebRTCConnectionManager -[#red]> WebRTCConnection: createConnection(channelRequirements)
activate WebRTCConnection

WebRTCConnection -> WebRTCConnection ++: beforeConnection() 호출
WebRTCConnection -> WebRTCConnection: 중복 없는 MosaicStore 리스트 생성
loop 각 MosaicStore
    WebRTCConnection -[#red]> MosaicStore ++: notifyBeforeConnected(robotId) 호출
    MosaicStore -> MosaicStore: beforeConnectedSubscribers 모두 호출
    MosaicStore -> MosaicStore: beforeConnected(robotId) 호출
    WebRTCConnection <[#blue]- MosaicStore --: 완료
end

WebRTCConnection -> WebRTCConnection: RobotConnector 별 MosaicStore 리스트 형식으로 정리 (ConnectorRequirement 생성)
WebRTCConnection <- WebRTCConnection --: ConnectorRequirement[] 반환

note right of WebRTCConnection
RTCPeerConnection 생성 및 저장
onicecandidate 이벤트 등록
onconnectionstatechange 등록
ondatachannel 이벤트 등록
end note

== MediaStream, DataChannel 생성 및 콜백 등록 ==
loop 각 ConnectorRequirement
    loop 각 MosaicStore
        WebRTCConnection -> MosaicStore: getStoreType()
        WebRTCConnection <- MosaicStore: storeType
        alt storeType === "receivable"
            WebRTCConnection -> MosaicStore: isParallelReceivable()
            WebRTCConnection <- MosaicStore: true | false
            opt true
                WebRTCConnection -> WebRTCConnection: robotConnector.parallel 조회, parallel 수만큼 아래 처리 반복
            end
            WebRTCConnection -[#red]> WebRTCConnection ++: createDataChannel(connectorId)
            WebRTCConnection -> WebRTCConnection: dataChannels Map 에 connectorId 를 key 로 생성한 RTCDataChannel 저장
            WebRTCConnection <[#blue]- WebRTCConnection --: RTCDataChannel 반환

            WebRTCConnection -[#red]> WebRTCConnection ++: setupReceivableChannel(RTCDataChannel, ReceivableStore)
            WebRTCConnection -> RTCDataChannel: onmessage 이벤트 등록
            note over WebRTCConnection, RTCDataChannel: onmessage 시 ReceivableStore 의 notifySubscribers(data) 호출
            WebRTCConnection <[#blue]- WebRTCConnection --: 완료
        else storeType === "sendable"
            WebRTCConnection -[#red]> WebRTCConnection ++: createDataChannel(connectorId)
            WebRTCConnection -> WebRTCConnection: dataChannels Map 에 connectorId 를 key 로 생성한 RTCDataChannel 저장
            WebRTCConnection <[#blue]- WebRTCConnection --: RTCDataChannel 반환

            WebRTCConnection -[#red]> WebRTCConnection ++: setupSendableChannel(RTCDataChannel, SendableStore)
            WebRTCConnection -[#red]> MosaicStore: SendableStore 의 setDataChannel(RTCDataChannel) 호출
            MosaicStore -> MosaicStore: RTCDataChannel 저장
            MosaicStore -[#blue]> WebRTCConnection: 완료
            WebRTCConnection <[#blue]- WebRTCConnection --: 완료
        else storeType === "media"
            WebRTCConnection -[#red]> WebRTCConnection: createMediaStream(connectorId)
            WebRTCConnection <[#blue]- WebRTCConnection: 완료
        end
    end
end

WebRTCConnectionManager <[#blue]- WebRTCConnection: 완료
deactivate WebRTCConnection

== SDP Offer 전송 ==
WebRTCConnectionManager -[#red]> WebRTCConnection: startConnection()
activate WebRTCConnection
WebRTCConnection -> WebRTCConnection ++: createSdpOffer()
WebRTCConnection -> WebRTCConnection: addTransceiver()
note right of WebRTCConnection: addTransceiver 를 꼭 호출해야 하는지 검토 필요.
WebRTCConnection -> WebRTCConnection --: RTCSessionDescriptionInit

WebRTCConnection -> WebRTCConnection: peerConnection.setLocalDescription(offer)

WebRTCConnection -[#red]> SignalingServer: sendSdpOffer(rtcConnectionId, offer)
activate SignalingServer
SignalingServer -[#red]> Backend: SDP Offer 전송
activate Backend
WebRTCConnection <[#blue]- SignalingServer: 완료
deactivate SignalingServer

WebRTCConnection -[#blue]> WebRTCConnectionManager: 완료
deactivate WebRTCConnection
WebRTCConnectionManager -[#blue]> MosaicContext: 완료
deactivate WebRTCConnectionManager
MosaicContext -[#blue]> DashboardGrid: 완료
deactivate MosaicContext

note right of DashboardGrid: startConnection() 종료\n이후 비동기 처리
note over SignalingServer, Robot
{
    "type": "send_sdp_offer",
    "rtcConnectionId": "d1c35a55-445c-4e5e-9451-34c42d74fcbd",
    "sdp_offer": "v=0\r\no=- 0 0 IN IP4..."
}
end note

Backend -[#red]> Robot: SDP Offer 전달
activate Robot
deactivate Backend

== SDP Answer 수신 ==

Robot -[#black]> Robot: SDP 처리 및 Answer 생성

Robot -[#blue]> Backend: SDP Answer 전송
activate Backend
deactivate Robot

note over SignalingServer, Robot
{
    "type": "send_sdp_answer",
    "rtcConnectionId": "d1c35a55-445c-4e5e-9451-34c42d74fcbd",
    "sdp_answer": "v=0\r\no=- 0 0 IN IP4..."
}
end note

Backend -[#red]> SignalingServer: SDP Answer 전달
activate SignalingServer
deactivate Backend

SignalingServer -> SignalingServer: receiveSdpAnswer 이벤트 실행
SignalingServer -> SignalingServer: rtcConnections Map 에서 rtcConnectionId 로 WebRTCConnection 조회
SignalingServer -[#red]> WebRTCConnection ++: receiveSdpAnswer(data)
WebRTCConnection -> WebRTCConnection: resolveSdpAnswer(data)
WebRTCConnection -> WebRTCConnection: peerConnection.setRemoteDescription(answer)
WebRTCConnection -[#blue]> SignalingServer --: 완료
deactivate SignalingServer

== ICE Candidate 수집 시 ==
WebRTCConnection -[#black]> WebRTCConnection: onicecandidate 이벤트 실행
activate WebRTCConnection
WebRTCConnection -[#red]> SignalingServer: sendIceCandidate(rtcConnectionId, candidate)
activate SignalingServer
SignalingServer -[#red]> Backend: ICE Candidate 전송
activate Backend

WebRTCConnection <[#blue]- SignalingServer: 완료
deactivate SignalingServer
WebRTCConnection -> WebRTCConnection: 완료
deactivate WebRTCConnection

note over SignalingServer, Robot
{
    "type": "exchange_ice_candidate",
    "rtcConnectionId": "d1c35a55-445c-4e5e-9451-34c42d74fcbd",
    "ice_candidate": {
        "candidate": "candidate:0 1 UDP 2122260223...",
        "sdpMid": "video",
        "sdpMLineIndex": 0
    }
}
end note

Backend -[#red]> Robot: SDP Offer 전달
activate Robot
deactivate Backend

Robot -[#black]> Robot: SDP 처리 및 Answer 생성
deactivate Robot
== ICE Candidate 수신 시 ==

Robot <-: Ice Candidate 수집
Robot -> Backend: ICE Candidate 전송

note over SignalingServer, Robot
{
    "type": "exchange_ice_candidate",
    "rtcConnectionId": "d1c35a55-445c-4e5e-9451-34c42d74fcbd",
    "ice_candidate": {
        "candidate": "candidate:0 1 UDP 2122260223...",
        "sdpMid": "video",
        "sdpMLineIndex": 0
    }
}
end note

Backend -> SignalingServer: ICE Candidate 전송
activate SignalingServer
SignalingServer -> SignalingServer: receiveIceCandidate 이벤트 실행
SignalingServer -> SignalingServer: rtcConnections Map 에서 rtcConnectionId 로 WebRTC Connection 조회
SignalingServer -[#red]> WebRTCConnection ++: receiveIceCandidate(data)
WebRTCConnection -> WebRTCConnection: resolveIceCandidate(data)
WebRTCConnection -> WebRTCConnection: peerConnection.addIceCandidate(candidate)
WebRTCConnection -[#blue]> SignalingServer --: 완료
deactivate SignalingServer

== 연결 상태 변경 (연결 완료, 끊어짐, 에러) ==

WebRTCConnection -[#black]> WebRTCConnection: onconnectionstatechange 이벤트 실행
activate WebRTCConnection

alt peerConnection.connectionState === "connected"
    WebRTCConnection -> WebRTCConnection ++: onConnectionConnected() 호출
    loop relatedStores 의 모든 MosaicStore
        WebRTCConnection -[#red]> MosaicStore: notifyAfterConnected(robotId) 호출
        MosaicStore -> MosaicStore: afterConnectedSubscribers 모두 호출
        MosaicStore -> MosaicStore: afterConnected(robotId) 호출
        WebRTCConnection <[#blue]- MosaicStore: 완료
    end
    WebRTCConnection -> WebRTCConnection --: 완료
else "disconnected"
    WebRTCConnection -> WebRTCConnection ++: onConnectionDisconnected() 호출
    loop relatedStores 의 모든 MosaicStore
        WebRTCConnection -[#red]> MosaicStore: notifyAfterDisconnected(robotId) 호출
        MosaicStore -> MosaicStore: afterDisconnectedSubscribers 모두 호출
        MosaicStore -> MosaicStore: afterDisconnected(robotId) 호출
        WebRTCConnection <[#blue]- MosaicStore: 완료
    end
    WebRTCConnection -> WebRTCConnection --: 완료
else "failed"
    WebRTCConnection -> WebRTCConnection ++: onConnectionDisconnected() 호출
    loop relatedStores 의 모든 MosaicStore
        WebRTCConnection -[#red]> MosaicStore: notifyAfterConnectionFailed(robotId) 호출
        MosaicStore -> MosaicStore: afterConnectionFailedSubscribers 모두 호출
        MosaicStore -> MosaicStore: afterConnectionFailed(robotId) 호출
        WebRTCConnection <[#blue]- MosaicStore: 완료
    end
    WebRTCConnection -> WebRTCConnection --: 완료
end
WebRTCConnection -> WebRTCConnection: 완료
deactivate WebRTCConnection

note right of DashboardGrid: UI 자동 업데이트 (async)\n(RobotInfo 상태 변경 감지)
@enduml